 /*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.table_data.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <net-snmp/agent/var_struct.h>
#include "netSnmpAmiHandle.hpp"
#include "netSnmpAmi.hpp"
#include "netSnmpHostsTable.hpp"

#include <signal.h>

#include <phosphor-logging/elog-errors.hpp>
#include <phosphor-logging/elog.hpp>
#include <phosphor-logging/lg2.hpp>


#include <sdbusplus/message/types.hpp>
#include <xyz/openbmc_project/Common/error.hpp>
#include <xyz/openbmc_project/Sensor/Value/server.hpp>
#include <iostream>

static amiHandleSensorTable_entry *sensorData_head = NULL;
static amiHandleDiscreteSensorTable_entry *discreteSensorData_head = NULL;
static amiHandleUserInfoTable_entry *userInfoData_head = NULL;

#define getUserName getSensorName
#if 0
void initialize_amiHandlers(void)
{
    int agentx_subagent=1;

    snmp_enable_stderrlog();

    /* we're an agentx subagent? */
    if (agentx_subagent)
    {
        /* make us a agentx client. */
        netsnmp_ds_set_boolean(NETSNMP_DS_APPLICATION_ID, NETSNMP_DS_AGENT_ROLE, 1);
    }

    SOCK_STARTUP;

    /* initialize the agent library */
    init_agent("ami-snmp-agent-deamon");

    init_netSnmpHostsTable();
    init_netSnmpAMIScalars();
    init_netSnmpAmiSensorTable();
    init_netSnmpAmiDiscreteSensorTable();
    init_netSnmpAmiUserInfoTable();
    init_snmp("ami-snmp-agent-deamon");

    int keep_running = 1;

    snmp_log(LOG_INFO,"ami-snmp-agent-deamon is up and running.\n");

    /* your main loop here... */
    /*Reason for False Positive - Logical, Need to run infinite loop*/
    /*coverity[INFINITE_LOOP : FALSE]*/
    while(keep_running)
    {
        agent_check_and_process(1); /* 0 == don't block */
    }

    /* at shutdown time */
    /*Reason for False Positive - Logical without wrong*/
    /*coverity[DEADCODE : FALSE]*/
    snmp_shutdown("ami-snmp-agent-deamon");
    SOCK_CLEANUP;

    return ;
}
#endif

std::string getSensorName(std::string Str)
{
    std::string sensorName;

    size_t pos = Str.find("/");

    while (pos != std::string::npos)
    {
        sensorName=Str.substr(0, pos);
        Str.erase(Str.begin(), Str.begin() + pos + 1);
        pos = Str.find("/");
    }
    sensorName=Str.substr(0,pos);
    return sensorName;
}

dbusPropVariant getDbusProperty(const std::string& service,
                                   const std::string& objPath,
                                   const std::string& interface,
                                   const std::string& property)
{
    dbusPropVariant Value;
    auto bus = sdbusplus::bus::new_default();
    try
    {
        auto method = bus.new_method_call(service.c_str(), objPath.c_str(),
                                          "org.freedesktop.DBus.Properties",
                                          "Get");

        method.append(interface, property);

        auto reply = bus.call(method);
        reply.read(Value);
    }
    catch (const sdbusplus::exception_t& e)
    {
        std::cerr << "Fail to getDbusProperty : " << e.what() << std::endl;
    }
    return Value;
}

void getSensorData(std::vector<amiHandleSensorTable_entry>& data)
{
        // Object Mapper related
    static constexpr const char* objMapperService =
      "xyz.openbmc_project.ObjectMapper";
    static constexpr const char* objMapperPath =
      "/xyz/openbmc_project/object_mapper";
    static constexpr const char* objMapperInterface =
      "xyz.openbmc_project.ObjectMapper";
    auto depth = 0;
    std::string iface = "xyz.openbmc_project.Sensor.Value";
    std::string value = "Value";
    std::string path = "/";

    using GetSubTreeType = std::vector<
    std::pair<std::string,
              std::vector<std::pair<std::string, std::vector<std::string>>>>>;

    GetSubTreeType mapperRead;
    try
    {
        auto bus = sdbusplus::bus::new_default();

        auto mapperCall = bus.new_method_call(objMapperService, objMapperPath,
                                              objMapperInterface, "GetSubTree");

        mapperCall.append(path);
        mapperCall.append(depth);
        mapperCall.append(std::vector<std::string>{iface});

        auto mapperResponse = bus.call(mapperCall);
        mapperResponse.read(mapperRead);
    }
    catch (const sdbusplus::exception_t& e)
    {
        std::cout << "Error in getSensorData" << std::endl ;
    }

    dbusPropVariant datafloatvariant;
    double datafloat;
    int index=1;
    amiHandleSensorTable_entry tmpData;
    std::memset(&tmpData, 0, sizeof(tmpData));
    for (const auto& outerPair : mapperRead) {
        for (const auto& innerPair : outerPair.second) {

            std::string service = innerPair.first.c_str();
            std::string path = outerPair.first.c_str();

            datafloatvariant=getDbusProperty(service,path,iface,value);

            if(auto ptr=std::get_if<double>(&datafloatvariant)){
		datafloat=*ptr;
	    }
	    else{
		datafloat=0;
	    }
	    std::string name = getSensorName(path);
	    tmpData.sensorIndex=index++;
	    std::strncpy(tmpData.sensorName, name.data(), sizeof(tmpData.sensorName)-1);
	    tmpData.sensorValue=datafloat;
	    data.push_back(tmpData);
	    std::memset(&tmpData, 0, sizeof(tmpData));
        }
    }
}

void AddToSensorInstances(struct amiHandleSensorTable_entry *sensorInst)
{
    struct amiHandleSensorTable_entry *ptr = NULL;
    if (sensorData_head == NULL)
    {
        sensorData_head = sensorInst;
    }
    else
    {
        ptr = sensorData_head;
        while (ptr->next != NULL)
	{
            ptr = ptr->next;
	}
        ptr->next = sensorInst;
    }
}


int
sensorTable_load(netsnmp_cache *cache, void *vmagic)
{
    struct amiHandleSensorTable_entry *table_entry = NULL;

    if(0)
    {
        cache=cache;
        vmagic=vmagic;
    }

    std::vector<amiHandleSensorTable_entry> sensorData;
    getSensorData(sensorData);

    for(auto it=sensorData.begin();it!=sensorData.end();it++)
    {
        table_entry = (struct amiHandleSensorTable_entry *) calloc(1, sizeof(struct amiHandleSensorTable_entry));
        table_entry->sensorIndex = it->sensorIndex;
        std::strncpy ( table_entry->sensorName , it->sensorName, (sizeof(it->sensorName)-1));
        table_entry->sensorValue  = it->sensorValue;
        table_entry->next = NULL;

        /*Adds the current sensor table as instance.*/
        AddToSensorInstances(table_entry);
    }

    return 0;
}

void
sensorTable_free(netsnmp_cache *cache, void *magic)
{
    struct amiHandleSensorTable_entry *entry = NULL;

    if(0)
    {
        cache=cache;
        magic=magic;
    }
    while (sensorData_head)
    {
        entry = sensorData_head;
        sensorData_head = sensorData_head->next;
        SNMP_FREE(entry);
    }
}


netsnmp_variable_list *
sensorTable_get_first_data_point(void **my_loop_context,
                               void **my_data_context,
                               netsnmp_variable_list * put_index_data,
                               netsnmp_iterator_info *mydata)
{

    *my_loop_context = sensorData_head;
    return sensorTable_get_next_data_point(my_loop_context, my_data_context,
                                         put_index_data, mydata);
}

netsnmp_variable_list *
sensorTable_get_next_data_point(void **my_loop_context,
                              void **my_data_context,
                              netsnmp_variable_list * put_index_data,
                              netsnmp_iterator_info *mydata)
{
    struct amiHandleSensorTable_entry *entry = (struct amiHandleSensorTable_entry *) *my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if(0)
    {
        mydata=mydata;
    }

    if (entry)
    {
        snmp_set_var_value(idx,(u_char *) &entry->sensorIndex,
                           sizeof(entry->sensorIndex));
        idx = idx->next_variable;
        *my_data_context = (void *) entry;
        *my_loop_context = (void *) entry->next;
        return put_index_data;
    }
    else
    {
        return NULL;
    }
}


/** Initialize the netSnmpAmiSensorTable table by defining its contents and how it's structured */
void
init_netSnmpAmiSensorTable(void)
{
    const oid netSnmpAmiSensorTable_oid[] = {1,3,6,1,4,1,20974,554,2};
    const size_t netSnmpAmiSensorTable_oid_len   = OID_LENGTH(netSnmpAmiSensorTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info *it_info = NULL;
    netsnmp_table_registration_info *table_info;
    int ret=0;

    reg = netsnmp_create_handler_registration("netSnmpAmiSensorTable",
                                              handler_netSnmpAmiSensorTable,
                                              netSnmpAmiSensorTable_oid,
                                              netSnmpAmiSensorTable_oid_len,
                                              HANDLER_CAN_RONLY);
    if(reg == NULL)
    {
	snmp_log(LOG_ERR,"error creating handle for netSnmpAmiSensorTable\n");
	return;
    }

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    if (NULL == table_info)
    {
        snmp_log(LOG_ERR,"error creating table info for netSnmpAmiSensorTable\n");
        netsnmp_handler_registration_free(reg);
        return;
    }
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER, 0);

    table_info->min_column = COLUMN_SENSORINDEX;
    table_info->max_column = COLUMN_SENSORVALUE;

    it_info = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
    if(it_info == NULL)
    {
        snmp_log(LOG_ERR,"error allocating memory for netsnmp_iterator_info \n");
        netsnmp_handler_registration_free(reg);
        SNMP_FREE(table_info);
        return;
    }
    it_info->get_first_data_point = sensorTable_get_first_data_point;
    it_info->get_next_data_point = sensorTable_get_next_data_point;
    it_info->table_reginfo = table_info;

    ret = netsnmp_register_table_iterator(reg, it_info);
    if(ret != 0)
    {
        snmp_log(LOG_ERR,"error in netsnmp_iterator_table_iterator \n");
        //netsnmp_handler_registration_free(reg); this resource freeing is already handled in netsnmp_register_table_iterator in case of failure
        SNMP_FREE(table_info);
        SNMP_FREE(it_info);
        return;
    }
    netsnmp_inject_handler_before(reg,netsnmp_get_cache_handler(REFRESH_RATE,
                    sensorTable_load, sensorTable_free,
                    netSnmpAmiSensorTable_oid, netSnmpAmiSensorTable_oid_len),NULL);

}

/** handles requests for the netSnmpAmiSensorTable table */
int
handler_netSnmpAmiSensorTable(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request=NULL;
    netsnmp_table_request_info *table_info=NULL;
    struct amiHandleSensorTable_entry *table_entry=NULL;

    if(0)
    {
        handler = handler;
        reginfo = reginfo;
    }

    if (reqinfo->mode == MODE_GET) {

        for (request=requests; request; request=request->next)
        {
            table_entry = (struct amiHandleSensorTable_entry *)
                                   netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            if (table_entry == NULL)
            {
                netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
                continue;
            }

            switch (table_info->colnum)
            {
              case COLUMN_SENSORINDEX:
                snmp_set_var_typed_value( request->requestvb, ASN_INTEGER,
                                          (u_char *)&table_entry->sensorIndex,
                                          sizeof(table_entry->sensorIndex));
                break;
              case COLUMN_SENSORNAME:
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          (u_char *)table_entry->sensorName,
                                          std::strlen(table_entry->sensorName));
                break;
              case COLUMN_SENSORVALUE:
                snmp_set_var_typed_value( request->requestvb, ASN_OPAQUE_DOUBLE,
                                            (u_char *)&table_entry->sensorValue,
					    sizeof(table_entry->sensorValue));
                break;
              default:
                netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHOBJECT);
                break;
             }
          }
    }

    return SNMP_ERR_NOERROR;
}

/*Discrete Sensor*/

void getDiscreteSensorData(std::vector<amiHandleDiscreteSensorTable_entry>& data)
{
        // Object Mapper related
    static constexpr const char* objMapperService =
      "xyz.openbmc_project.ObjectMapper";
    static constexpr const char* objMapperPath =
      "/xyz/openbmc_project/object_mapper";
    static constexpr const char* objMapperInterface =
      "xyz.openbmc_project.ObjectMapper";
    auto depth = 0;
    std::string iface = "xyz.openbmc_project.Sensor.State";
    std::string value = "State";
    std::string path = "/";

    using GetSubTreeType = std::vector<std::pair<std::string,
              std::vector<std::pair<std::string, std::vector<std::string>>>>>;

    GetSubTreeType mapperRead;
    try
    {
        auto bus = sdbusplus::bus::new_default();

        auto mapperCall = bus.new_method_call(objMapperService, objMapperPath,
                                              objMapperInterface, "GetSubTree");

        mapperCall.append(path);
        mapperCall.append(depth);
        mapperCall.append(std::vector<std::string>{iface});

        auto mapperResponse = bus.call(mapperCall);
        mapperResponse.read(mapperRead);
    }
    catch (const sdbusplus::exception_t& e)
    {
        std::cout << "Error in getDiscreteSensorData" << std::endl ;
    }

    dbusPropVariant dataVariant;
    uint16_t udata;
    int index=1;
    amiHandleDiscreteSensorTable_entry tmpData;
    std::memset(&tmpData, 0, sizeof(tmpData));
    for (const auto& outerPair : mapperRead) {
        for (const auto& innerPair : outerPair.second) {

            std::string service = innerPair.first.c_str();
            std::string path = outerPair.first.c_str();

            dataVariant=getDbusProperty(service,path,iface,value);

            if(auto ptr=std::get_if<uint16_t>(&dataVariant)){
                udata=*ptr;
            }
            else{
                udata=0;
            }
            std::string name = getSensorName(path);
            tmpData.sensorIndex=index++;
            std::strncpy(tmpData.sensorName, name.data(), sizeof(tmpData.sensorName)-1);
            tmpData.sensorValue=udata;
            data.push_back(tmpData);
            std::memset(&tmpData, 0, sizeof(tmpData));
        }
    }
}

void AddToDiscreteSensorInstances(struct amiHandleDiscreteSensorTable_entry *sensorInst)
{
    struct amiHandleDiscreteSensorTable_entry *ptr = NULL;
    if (discreteSensorData_head == NULL)
    {
        discreteSensorData_head = sensorInst;
    }
    else
    {
        ptr = discreteSensorData_head;
        while (ptr->next != NULL)
        {
            ptr = ptr->next;
        }
        ptr->next = sensorInst;
    }
}


int
discreteSensorTable_load(netsnmp_cache *cache, void *vmagic)
{
    struct amiHandleDiscreteSensorTable_entry *table_entry = NULL;

    if(0)
    {
        cache=cache;
        vmagic=vmagic;
    }

    std::vector<amiHandleDiscreteSensorTable_entry> sensorData;
    getDiscreteSensorData(sensorData);

    for(auto it=sensorData.begin();it!=sensorData.end();it++)
    {
        table_entry = (struct amiHandleDiscreteSensorTable_entry *) calloc(1, sizeof(struct amiHandleDiscreteSensorTable_entry));
        table_entry->sensorIndex = it->sensorIndex;
        std::strncpy ( table_entry->sensorName , it->sensorName, (sizeof(it->sensorName)-1));
        table_entry->sensorValue  = it->sensorValue;
        table_entry->next = NULL;

        /*Adds the current sensor table as instance.*/
        AddToDiscreteSensorInstances(table_entry);
    }

    return 0;
}

void
discreteSensorTable_free(netsnmp_cache *cache, void *magic)
{
    struct amiHandleDiscreteSensorTable_entry *entry = NULL;

    if(0)
    {
        cache=cache;
        magic=magic;
    }
    while (discreteSensorData_head)
    {
        entry = discreteSensorData_head;
        discreteSensorData_head = discreteSensorData_head->next;
        SNMP_FREE(entry);
    }
}


netsnmp_variable_list *
discreteSensorTable_get_first_data_point(void **my_loop_context,
                               void **my_data_context,
                               netsnmp_variable_list * put_index_data,
                               netsnmp_iterator_info *mydata)
{

    *my_loop_context = discreteSensorData_head;
    return discreteSensorTable_get_next_data_point(my_loop_context, my_data_context,
                                         put_index_data, mydata);
}

netsnmp_variable_list *
discreteSensorTable_get_next_data_point(void **my_loop_context,
                              void **my_data_context,
                              netsnmp_variable_list * put_index_data,
                              netsnmp_iterator_info *mydata)
{
    struct amiHandleDiscreteSensorTable_entry *entry = (struct amiHandleDiscreteSensorTable_entry *) *my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if(0)
    {
        mydata=mydata;
    }

    if (entry)
    {
        snmp_set_var_value(idx,(u_char *) &entry->sensorIndex,
                           sizeof(entry->sensorIndex));
        idx = idx->next_variable;
        *my_data_context = (void *) entry;
        *my_loop_context = (void *) entry->next;
        return put_index_data;
    }
    else
    {
        return NULL;
    }
}


/** Initialize the netSnmpAmiDiscreteSensorTable table by defining its contents and how it's structured */
void
init_netSnmpAmiDiscreteSensorTable(void)
{
    const oid netSnmpAmiDiscreteSensorTable_oid[] = {1,3,6,1,4,1,20974,554,4};
    const size_t netSnmpAmiDiscreteSensorTable_oid_len   = OID_LENGTH(netSnmpAmiDiscreteSensorTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info *it_info = NULL;
    netsnmp_table_registration_info *table_info;
    int ret=0;

    reg = netsnmp_create_handler_registration("netSnmpAmiDiscreteSensorTable",
                                              handler_netSnmpAmiDiscreteSensorTable,
                                              netSnmpAmiDiscreteSensorTable_oid,
                                              netSnmpAmiDiscreteSensorTable_oid_len,
                                              HANDLER_CAN_RONLY);
    if(reg == NULL)
    {
        snmp_log(LOG_ERR,"error creating handle for netSnmpAmiSensorTable\n");
        return;
    }

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    if (NULL == table_info)
    {
        snmp_log(LOG_ERR,"error creating table info for netSnmpAmiSensorTable\n");
        netsnmp_handler_registration_free(reg);
        return;
    }
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER, 0);

    table_info->min_column = COLUMN_SENSORINDEX;
    table_info->max_column = COLUMN_SENSORVALUE;

    it_info = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
    if(it_info == NULL)
    {
        snmp_log(LOG_ERR,"error allocating memory for netsnmp_iterator_info \n");
        netsnmp_handler_registration_free(reg);
        SNMP_FREE(table_info);
        return;
    }
    it_info->get_first_data_point = discreteSensorTable_get_first_data_point;
    it_info->get_next_data_point = discreteSensorTable_get_next_data_point;
    it_info->table_reginfo = table_info;

    ret = netsnmp_register_table_iterator(reg, it_info);
    if(ret != 0)
    {
        snmp_log(LOG_ERR,"error in netsnmp_iterator_table_iterator \n");
        //netsnmp_handler_registration_free(reg); this resource freeing is already handled in netsnmp_register_table_iterator in case of failure
        SNMP_FREE(table_info);
        SNMP_FREE(it_info);
        return;
    }

    netsnmp_inject_handler_before(reg,netsnmp_get_cache_handler(REFRESH_RATE,
                    discreteSensorTable_load, discreteSensorTable_free,
                    netSnmpAmiDiscreteSensorTable_oid, netSnmpAmiDiscreteSensorTable_oid_len),NULL);

}

/** handles requests for the netSnmpAmiDiscreteSensorTable table */
int
handler_netSnmpAmiDiscreteSensorTable(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request=NULL;
    netsnmp_table_request_info *table_info=NULL;
    struct amiHandleDiscreteSensorTable_entry *table_entry=NULL;

    if(0)
    {
        handler = handler;
        reginfo = reginfo;
    }

    if (reqinfo->mode == MODE_GET) {

        for (request=requests; request; request=request->next)
        {
            table_entry = (struct amiHandleDiscreteSensorTable_entry *)
                                   netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info(request);

            if (table_entry == NULL)
            {
                netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
                continue;
            }

            switch (table_info->colnum)
            {
              case COLUMN_SENSORINDEX:
                snmp_set_var_typed_value( request->requestvb, ASN_INTEGER,
                                          (u_char *)&table_entry->sensorIndex,
                                          sizeof(table_entry->sensorIndex));
                break;
              case COLUMN_SENSORNAME:
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          (u_char *)table_entry->sensorName,
                                          std::strlen(table_entry->sensorName));
                break;
              case COLUMN_SENSORVALUE:
                snmp_set_var_typed_value( request->requestvb, ASN_UNSIGNED,
                                            (u_char *)&table_entry->sensorValue,
                                            sizeof(table_entry->sensorValue));
                break;
              default:
                netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHOBJECT);
                break;
             }
          }
    }

    return SNMP_ERR_NOERROR;
}

void AddToUserInfoInstances(struct amiHandleUserInfoTable_entry *userInst)
{
    struct amiHandleUserInfoTable_entry *ptr = NULL;
    if (userInfoData_head == NULL)
    {
        userInfoData_head = userInst;
    }
    else
    {
        ptr = userInfoData_head;
        while (ptr->next != NULL)
        {
            ptr = ptr->next;
        }
        ptr->next = userInst;
    }
}


void getUserInfo(std::vector<amiHandleUserInfoTable_entry>& data)
{
        // Object Mapper related
    static constexpr const char* objMapperService =
      "xyz.openbmc_project.ObjectMapper";
    static constexpr const char* objMapperPath =
      "/xyz/openbmc_project/object_mapper";
    static constexpr const char* objMapperInterface =
      "xyz.openbmc_project.ObjectMapper";
    auto depth = 0;
    std::string iface = "xyz.openbmc_project.User.Attributes";
    std::string path = "/";

    using GetSubTreeType = std::vector<std::string>;

    GetSubTreeType mapperRead;
    try
    {
        auto bus = sdbusplus::bus::new_default();

        auto mapperCall = bus.new_method_call(objMapperService, objMapperPath,
                                              objMapperInterface, "GetSubTreePaths");

        mapperCall.append(path);
        mapperCall.append(depth);
        mapperCall.append(std::vector<std::string>{iface});

        auto mapperResponse = bus.call(mapperCall);
        mapperResponse.read(mapperRead);
    }
    catch (const sdbusplus::exception_t& e)
    {
        std::cout << "Error in getUserInfo" << std::endl ;
    }

    constexpr const char* UserName = "UserName";
    constexpr const char* RemoteUser = "RemoteUser";
    constexpr const char* TwoFacEnableStatus = "TwoFacEnableStatus";
    constexpr const char* UserEnabled = "UserEnabled";
    constexpr const char* UserGroups = "UserGroups";
    constexpr const char* UserLockedForFailedAttempt = "UserLockedForFailedAttempt";
    constexpr const char* UserPasswordExpired = "UserPasswordExpired";
    constexpr const char* UserPrivilege = "UserPrivilege";

    dbusPropVariant dataVariant;
    int index=1;
    amiHandleUserInfoTable_entry tmpData;
    static constexpr const char* service = "xyz.openbmc_project.User.Manager";

    std::memset(&tmpData, 0, sizeof(tmpData));

    std::string formatted_string;
    std::string str;

    for (const auto& it : mapperRead) {

            tmpData.userIndex=index++;

            std::string name = getUserName(it);

  	    formatted_string = std::format("{}={}",UserName,name);

            dataVariant=getDbusProperty(service,it,iface,RemoteUser);

            if(auto ptr=std::get_if<bool>(&dataVariant)){
                str=(*ptr ? "true" : "false");
            }

  	    formatted_string += std::format(", {}={}",RemoteUser,str);

            dataVariant=getDbusProperty(service,it,iface,TwoFacEnableStatus);

            if(auto ptr=std::get_if<bool>(&dataVariant)){
                str=(*ptr ? "true" : "false");
            }

  	    formatted_string += std::format(", {}={}",TwoFacEnableStatus,str);

            dataVariant=getDbusProperty(service,it,iface,UserEnabled);

            if(auto ptr=std::get_if<bool>(&dataVariant)){
                str=(*ptr ? "true" : "false");
            }

  	    formatted_string += std::format(", {}={}",UserEnabled,str);


            dataVariant=getDbusProperty(service,it,iface,UserGroups);

            if(auto ptr=std::get_if<std::vector<std::string>>(&dataVariant)){
		str = "{";
                for (const auto& tmpstr : *ptr) {
        	    str+= tmpstr + ", ";
    		}
                if (str.length() >= 2 && str.substr(str.length() - 2) == ", ") {
                    str.erase(str.length() - 2);
                }
		str+="}";
            }

  	    formatted_string += std::format(", {}={}",UserGroups,str);


            dataVariant=getDbusProperty(service,it,iface,UserLockedForFailedAttempt);

            if(auto ptr=std::get_if<bool>(&dataVariant)){
                str=(*ptr ? "true" : "false");
            }

  	    formatted_string += std::format(", {}={}",UserLockedForFailedAttempt,str);

            dataVariant=getDbusProperty(service,it,iface,UserPasswordExpired);

            if(auto ptr=std::get_if<bool>(&dataVariant)){
                str=(*ptr ? "true" : "false");
            }

  	    formatted_string += std::format(", {}={}",UserPasswordExpired,str);

            dataVariant=getDbusProperty(service,it,iface,UserPrivilege);

            if(auto ptr=std::get_if<std::string>(&dataVariant)){
		str=*ptr;
            }

  	    formatted_string += std::format(", {}={}",UserPrivilege,str);

	    std::strncpy(tmpData.userInfo,formatted_string.data(),sizeof(tmpData.userInfo)-1);

            data.push_back(tmpData);
            std::memset(&tmpData, 0, sizeof(tmpData));
	    formatted_string.clear();
	    str.clear();
    }
}

int
userInfoTable_load(netsnmp_cache *cache, void *vmagic)
{
    struct amiHandleUserInfoTable_entry *table_entry = NULL;

    if(0)
    {
        cache=cache;
        vmagic=vmagic;
    }

    std::vector<amiHandleUserInfoTable_entry> userInfoData;
    getUserInfo(userInfoData);

    for(auto it=userInfoData.begin();it!=userInfoData.end();it++)
    {
        table_entry = (struct amiHandleUserInfoTable_entry *) calloc(1, sizeof(struct amiHandleUserInfoTable_entry));
        table_entry->userIndex = it->userIndex;
        std::strncpy ( table_entry->userInfo , it->userInfo, (sizeof(it->userInfo)-1));

        AddToUserInfoInstances(table_entry);
    }

    return 0;
}


void
userInfoTable_free(netsnmp_cache *cache, void *magic)
{
    struct amiHandleUserInfoTable_entry *entry = NULL;

    if(0)
    {
        cache=cache;
        magic=magic;
    }
    while (userInfoData_head)
    {
        entry = userInfoData_head;
        userInfoData_head = userInfoData_head->next;
        SNMP_FREE(entry);
    }
}


netsnmp_variable_list *
userInfoTable_get_first_data_point(void **my_loop_context,
                               void **my_data_context,
                               netsnmp_variable_list * put_index_data,
                               netsnmp_iterator_info *mydata)
{

    *my_loop_context = userInfoData_head;
    return userInfoTable_get_next_data_point(my_loop_context, my_data_context,
                                         put_index_data, mydata);
}

netsnmp_variable_list *
userInfoTable_get_next_data_point(void **my_loop_context,
                              void **my_data_context,
                              netsnmp_variable_list * put_index_data,
                              netsnmp_iterator_info *mydata)
{
    struct amiHandleUserInfoTable_entry *entry = (struct amiHandleUserInfoTable_entry *) *my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if(0)
    {
        mydata=mydata;
    }

    if (entry)
    {
        snmp_set_var_value(idx,(u_char *) &entry->userIndex,
                           sizeof(entry->userIndex));
        idx = idx->next_variable;
        *my_data_context = (void *) entry;
        *my_loop_context = (void *) entry->next;
        return put_index_data;
    }
    else
    {
        return NULL;
    }
}


void init_netSnmpAmiUserInfoTable(void)
{
    const oid netSnmpAmiUserInfoTable_oid[] = {1,3,6,1,4,1,20974,554,5};
    const size_t netSnmpAmiUserInfoTable_oid_len   = OID_LENGTH(netSnmpAmiUserInfoTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info *it_info = NULL;
    netsnmp_table_registration_info *table_info;
    int ret=0;

    reg = netsnmp_create_handler_registration("netSnmpAmiUserInfoTable",
                                              handler_netSnmpAmiUserInfoTable,
                                              netSnmpAmiUserInfoTable_oid,
                                              netSnmpAmiUserInfoTable_oid_len,
                                              HANDLER_CAN_RONLY);
    if(reg == NULL)
    {
        snmp_log(LOG_ERR,"error creating handle for netSnmpAmiUserInfoTable\n");
        return;
    }

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    if (NULL == table_info)
    {
        snmp_log(LOG_ERR,"error creating table info for netSnmpAmiUserInfoTable\n");
        netsnmp_handler_registration_free(reg);
        return;
    }
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER, 0);

    table_info->min_column = COLUMN_USERINDEX;
    table_info->max_column = COLUMN_USERINFO;

    it_info = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
    if(it_info == NULL)
    {
        snmp_log(LOG_ERR,"error allocating memory for netsnmp_iterator_info \n");
        netsnmp_handler_registration_free(reg);
        SNMP_FREE(table_info);
        return;
    }
    it_info->get_first_data_point = userInfoTable_get_first_data_point;
    it_info->get_next_data_point = userInfoTable_get_next_data_point;
    it_info->table_reginfo = table_info;

    ret = netsnmp_register_table_iterator(reg, it_info);
    if(ret != 0)
    {
        snmp_log(LOG_ERR,"error in netsnmp_iterator_table_iterator \n");
        //netsnmp_handler_registration_free(reg); this resource freeing is already handled in netsnmp_register_table_iterator in case of failure
        SNMP_FREE(table_info);
        SNMP_FREE(it_info);
        return;
    }

    netsnmp_inject_handler_before(reg,netsnmp_get_cache_handler(REFRESH_RATE,
                    userInfoTable_load, userInfoTable_free,
                    netSnmpAmiUserInfoTable_oid, netSnmpAmiUserInfoTable_oid_len),NULL);

}



/** handles requests for the netSnmpAmiUserInfoTable table */
int
handler_netSnmpAmiUserInfoTable(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request=NULL;
    netsnmp_table_request_info *table_info=NULL;
    struct amiHandleUserInfoTable_entry *table_entry=NULL;

    if(0)
    {
        handler = handler;
        reginfo = reginfo;
    }

    if (reqinfo->mode == MODE_GET) {

        for (request=requests; request; request=request->next)
        {
            table_entry = (struct amiHandleUserInfoTable_entry *) netsnmp_extract_iterator_context(request);
            table_info = netsnmp_extract_table_info( request);

            if ( table_entry == NULL )
            {
                netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
                continue;
            }

            switch (table_info->colnum)
            {
              case COLUMN_USERINDEX:
                snmp_set_var_typed_value( request->requestvb, ASN_INTEGER,
                                          (u_char *)&table_entry->userIndex,
                                          sizeof(table_entry->userIndex));
                break;
              case COLUMN_USERINFO:
                 snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          (u_char *)(table_entry->userInfo),
                                          std::strlen(table_entry->userInfo));
                break;
              default:
                netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHOBJECT);
                break;
              }
        }
    }

    return SNMP_ERR_NOERROR;
}

